global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # Node.js applications
  - job_name: 'labguard-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'labguard-web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: /metrics
    scrape_interval: 15s

  # Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Background worker
  - job_name: 'labguard-worker'
    static_configs:
      - targets: ['worker:3001']
    metrics_path: /metrics
    scrape_interval: 15s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['web:3000', 'api:3001', 'worker:3001']
    metrics_path: /health
    scrape_interval: 30s 